name: FP
version: 1.0.0.0
synopsis: Regular languages in Haskell. Finite automata and regular expressions
description: See FP.pdf
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - FP

tests:
  tests:
    main: tests.lhs
    source-dirs: test
    dependencies:
      - FP
      - QuickCheck
      - hspec
